version: '3.1'

services:
  db:
    image: mysql
    container_name: joomla_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123

  phpMyAdmin:
    image: phpmyadmin/phpmyadmin
    container_name: joomla_phpMyAdmin
    restart: always
    ports:
      - 8082:80
    depends_on:
      - "db"

  joomla:
    image: joomla
    container_name: joomla_app
    restart: always
    ports:
      - 8081:80
    environment:
      JOOMLA_DB_HOST: db
      JOOMLA_DB_NAME: joomla
      JOOMLA_DB_USER: root
      JOOMLA_DB_PASSWORD: admin123
    depends_on:
      - "db"